"""Add cascade delete to product relationships

Revision ID: 0a7dee3d4191
Revises: 294e4f48bbcd
Create Date: 2025-05-28 11:17:11.023950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7dee3d4191'
down_revision = '294e4f48bbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_favorites_product_id_products'), 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_favorites_product_id_products'), 'favorites', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_transactions_product_id_products'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_product_id_products'), 'transactions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_product_id_products'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_product_id_products'), 'transactions', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('fk_favorites_product_id_products'), 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_favorites_product_id_products'), 'favorites', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
